namespace HabiticaPetFeeder.App
{
    public class UserFetchResponseDataPets
    {
        public int LionCubWhite { get; set; }
        public int DragonRoyalPurple { get; set; }
        public int CactusDesert { get; set; }
        public int DragonSkeleton { get; set; }
        public int WolfBase { get; set; }
        public int TigerCubBase { get; set; }
        public int PandaCubBase { get; set; }
        public int LionCubBase { get; set; }
        public int FoxBase { get; set; }
        public int FlyingPigBase { get; set; }
        public int DragonBase { get; set; }
        public int CactusBase { get; set; }
        public int BearCubBase { get; set; }
        public int WolfRoyalPurple { get; set; }
        public int TigerCubRoyalPurple { get; set; }
        public int PandaCubRoyalPurple { get; set; }
        public int LionCubRoyalPurple { get; set; }
        public int FoxRoyalPurple { get; set; }
        public int FlyingPigRoyalPurple { get; set; }
        public int CactusRoyalPurple { get; set; }
        public int BearCubRoyalPurple { get; set; }
        public int DragonWhite { get; set; }
        public int DragonDesert { get; set; }
        public int DragonRed { get; set; }
        public int DragonShade { get; set; }
        public int DragonZombie { get; set; }
        public int DragonCottonCandyPink { get; set; }
        public int DragonCottonCandyBlue { get; set; }
        public int DragonGolden { get; set; }
        public int JackOLanternBase { get; set; }
        public int WolfWhite { get; set; }
        public int WolfDesert { get; set; }
        public int WolfRed { get; set; }
        public int WolfShade { get; set; }
        public int WolfSkeleton { get; set; }
        public int WolfZombie { get; set; }
        public int WolfCottonCandyPink { get; set; }
        public int WolfCottonCandyBlue { get; set; }
        public int WolfGolden { get; set; }
        public int CactusWhite { get; set; }
        public int CactusRed { get; set; }
        public int CactusShade { get; set; }
        public int CactusSkeleton { get; set; }
        public int CactusZombie { get; set; }
        public int CactusCottonCandyPink { get; set; }
        public int CactusCottonCandyBlue { get; set; }
        public int CactusGolden { get; set; }
        public int BearCubSkeleton { get; set; }
        public int FlyingPigSkeleton { get; set; }
        public int FoxSkeleton { get; set; }
        public int LionCubSkeleton { get; set; }
        public int PandaCubSkeleton { get; set; }
        public int TigerCubSkeleton { get; set; }
        public int TigerCubWhite { get; set; }
        public int TigerCubDesert { get; set; }
        public int TigerCubRed { get; set; }
        public int TigerCubShade { get; set; }
        public int TigerCubCottonCandyPink { get; set; }
        public int TigerCubZombie { get; set; }
        public int TigerCubCottonCandyBlue { get; set; }
        public int TigerCubGolden { get; set; }
        public int PandaCubWhite { get; set; }
        public int PandaCubDesert { get; set; }
        public int PandaCubRed { get; set; }
        public int PandaCubShade { get; set; }
        public int PandaCubZombie { get; set; }
        public int PandaCubCottonCandyPink { get; set; }
        public int PandaCubCottonCandyBlue { get; set; }
        public int PandaCubGolden { get; set; }
        public int LionCubDesert { get; set; }
        public int LionCubShade { get; set; }
        public int LionCubRed { get; set; }
        public int LionCubZombie { get; set; }
        public int LionCubCottonCandyPink { get; set; }
        public int LionCubCottonCandyBlue { get; set; }
        public int LionCubGolden { get; set; }
        public int FoxWhite { get; set; }
        public int FoxDesert { get; set; }
        public int FoxRed { get; set; }
        public int FoxShade { get; set; }
        public int FoxZombie { get; set; }
        public int FoxCottonCandyPink { get; set; }
        public int FoxCottonCandyBlue { get; set; }
        public int FoxGolden { get; set; }
        public int FlyingPigWhite { get; set; }
        public int FlyingPigDesert { get; set; }
        public int FlyingPigRed { get; set; }
        public int FlyingPigShade { get; set; }
        public int FlyingPigZombie { get; set; }
        public int FlyingPigCottonCandyPink { get; set; }
        public int FlyingPigCottonCandyBlue { get; set; }
        public int FlyingPigGolden { get; set; }
        public int BearCubWhite { get; set; }
        public int BearCubDesert { get; set; }
        public int BearCubRed { get; set; }
        public int BearCubShade { get; set; }
        public int BearCubZombie { get; set; }
        public int BearCubCottonCandyPink { get; set; }
        public int BearCubCottonCandyBlue { get; set; }
        public int BearCubGolden { get; set; }
        public int TurkeyBase { get; set; }
        public int OrcaBase { get; set; }
        public int GryphonRoyalPurple { get; set; }
    }
}